export const OBTENER_PRODUCTOS_OK = 'OBTENER_PRODUCTOS_OK';
export const SELECCIONAR_PRODUCTOS = 'SELECCIONAR_PRODUCTOS';
export const CONFIRMAR_ORDEN_PLATO = 'CONFIRMAR_ORDEN_PLATO';
export const MOSTRAR_RESUMEN = ' MOSTRAR_RESUMEN';
export const ELIMINAR_PRODUCTO = 'ELIMINAR_PRODUCTO';
export const PEDIDO_ORDENADO = 'PEDIDO ORDENADO';